// Package table is a customized implementation of the simple table implementation
// at "charm.land/bubbles/v2/table".
package table

import (
	"strings"

	"charm.land/bubbles/v2/help"
	"charm.land/bubbles/v2/key"
	"charm.land/bubbles/v2/viewport"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/charmbracelet/x/ansi"
)

// Model defines a state for the table widget.
type Model struct {
	KeyMap *KeyMap
	Help   help.Model

	dynCols bool

	cols []Column
	// TODO: if rows are already stored in memory in their entirety, can't they
	// 'simply' be passed off to the viewport in their entirety, instead of the
	// complicated viewport content updates that also re-renders every visible
	// line each time.
	rows []Row

	// virtual rows replace rows (visually) when len > 0
	// virtual rows can be used to show filtered data
	virtualRows []Row
	cursor      int
	lastCursor  int // used to reset cursor after a virtual row reset
	focus       bool
	styles      Styles

	content viewport.Model
	header  viewport.Model

	// start & end represent the row indices of the content that is offered to
	// the content viewport, which in this implementation is equal to the rows
	// that are visible.
	start int // inclusive
	end   int // exclusive
}

// Row represents one line in the table.
type Row []string

func (r Row) String() string {
	return strings.Join(r, " ")
}

// Column defines the table structure.
type Column struct {
	Title string
	Width int
}

// KeyMap defines keybindings. It satisfies to the help.KeyMap interface, which
// is used to render the help menu.
type KeyMap struct {
	LineUp       key.Binding
	LineDown     key.Binding
	ScrollRight  key.Binding
	ScrollLeft   key.Binding
	PageUp       key.Binding
	PageDown     key.Binding
	HalfPageUp   key.Binding
	HalfPageDown key.Binding
	GotoTop      key.Binding
	GotoBottom   key.Binding
}

// ShortHelp implements the KeyMap interface.
func (km *KeyMap) ShortHelp() []key.Binding {
	return []key.Binding{km.LineUp, km.LineDown, km.ScrollLeft, km.ScrollRight}
}

// FullHelp implements the KeyMap interface.
func (km *KeyMap) FullHelp() [][]key.Binding {
	return [][]key.Binding{
		{km.LineUp, km.LineDown, km.GotoTop, km.GotoBottom},
		{km.ScrollLeft}, {km.ScrollRight},
		{km.PageUp, km.PageDown, km.HalfPageUp, km.HalfPageDown},
	}
}

// DefaultKeyMap returns a default set of keybindings.
func DefaultKeyMap() *KeyMap {
	return &KeyMap{
		LineUp: key.NewBinding(
			key.WithKeys("up", "k"),
			key.WithHelp("↑/k", "up"),
		),
		LineDown: key.NewBinding(
			key.WithKeys("down", "j"),
			key.WithHelp("↓/j", "down"),
		),
		ScrollRight: key.NewBinding(
			key.WithKeys("right", "l"),
			key.WithHelp("→/l", "right"),
		),
		ScrollLeft: key.NewBinding(
			key.WithKeys("left", "h"),
			key.WithHelp("←/h", "left"),
		),
		PageUp: key.NewBinding(
			key.WithKeys("b", "pgup"),
			key.WithHelp("b/pgup", "page up"),
		),
		PageDown: key.NewBinding(
			key.WithKeys("f", "pgdown", "space"),
			key.WithHelp("f/pgdn", "page down"),
		),
		HalfPageUp: key.NewBinding(
			key.WithKeys("u", "ctrl+u"),
			key.WithHelp("u", "½ page up"),
		),
		HalfPageDown: key.NewBinding(
			key.WithKeys("d", "ctrl+d"),
			key.WithHelp("d", "½ page down"),
		),
		GotoTop: key.NewBinding(
			key.WithKeys("home", "g"),
			key.WithHelp("g/home", "go to start"),
		),
		GotoBottom: key.NewBinding(
			key.WithKeys("end", "G"),
			key.WithHelp("G/end", "go to end"),
		),
	}
}

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header   lipgloss.Style
	Cell     lipgloss.Style
	Selected lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this table.
func DefaultStyles() Styles {
	return Styles{
		Selected: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("212")),
		Header:   lipgloss.NewStyle().Bold(true).Padding(0, 1),
		Cell:     lipgloss.NewStyle().Padding(0, 1),
	}
}

// SetStyles sets the table styles.
func (m *Model) SetStyles(s Styles) {
	m.styles = s
	m.UpdateContent()
}

// Option is used to set options in New. For example:
//
//	table := New(WithColumns([]Column{{Title: "ID", Width: 10}}))
type Option func(*Model)

// New creates a new model for the table widget.
func New(opts ...Option) *Model {
	step := 5
	h := viewport.New(viewport.WithHeight(2)) // header
	h.SoftWrap = false                        // disable text-wrap and allow horizontal scroll
	h.SetHorizontalStep(step)
	c := viewport.New(viewport.WithHeight(20)) // content
	c.SoftWrap = h.SoftWrap
	c.SetHorizontalStep(step)
	m := Model{
		cursor:  0,
		content: c, //nolint:mnd
		header:  h,

		dynCols: true,

		KeyMap: DefaultKeyMap(),
		Help:   help.New(),
		styles: DefaultStyles(),
	}

	for _, opt := range opts {
		opt(&m)
	}

	m.UpdateContent()

	return &m
}

func WithDynamicColumnWidth(b bool) Option {
	return func(m *Model) {
		m.dynCols = b
	}
}

// WithColumns sets the table columns (headers).
func WithColumns(cols []Column) Option {
	return func(m *Model) {
		m.cols = cols
	}
}

// WithRows sets the table rows (data).
func WithRows(rows []Row) Option {
	return func(m *Model) {
		m.rows = rows
	}
}

// WithVirtualRows sets the table virtual rows (data view).
func WithVirtualRows(rows []Row) Option {
	return func(m *Model) {
		m.virtualRows = rows
	}
}

// WithHeight sets the height of the table.
func WithHeight(h int) Option {
	return func(m *Model) {
		m.content.SetHeight(h - lipgloss.Height(m.renderHeader()))
	}
}

// WithWidth sets the width of the table.
func WithWidth(w int) Option {
	return func(m *Model) {
		m.content.SetWidth(w)
	}
}

// WithFocused sets the focus state of the table.
func WithFocused(f bool) Option {
	return func(m *Model) {
		m.focus = f
	}
}

// WithStyles sets the table styles.
func WithStyles(s Styles) Option {
	return func(m *Model) {
		m.styles = s
	}
}

// WithKeyMap sets the key map.
func WithKeyMap(km KeyMap) Option {
	return func(m *Model) {
		m.KeyMap = &km
	}
}

// Update is the Bubble Tea update loop.
func (m *Model) Update(msg tea.Msg) tea.Cmd {
	if !m.focus {
		return nil
	}

	switch msg := msg.(type) {
	case tea.KeyPressMsg:
		switch {
		case key.Matches(msg, m.KeyMap.LineUp):
			m.MoveUp(1)
		case key.Matches(msg, m.KeyMap.LineDown):
			m.MoveDown(1)
		case key.Matches(msg, m.KeyMap.ScrollRight):
			m.ScrollRight(1)
		case key.Matches(msg, m.KeyMap.ScrollLeft):
			m.ScrollLeft(1)
		case key.Matches(msg, m.KeyMap.PageUp):
			m.MoveUp(m.content.Height())
		case key.Matches(msg, m.KeyMap.PageDown):
			m.MoveDown(m.content.Height())
		case key.Matches(msg, m.KeyMap.HalfPageUp):
			m.MoveUp(m.content.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.HalfPageDown):
			m.MoveDown(m.content.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.GotoTop):
			m.GotoTop()
		case key.Matches(msg, m.KeyMap.GotoBottom):
			m.GotoBottom()
		}
	}

	return nil
}

// Focused returns the focus state of the table.
func (m *Model) Focused() bool {
	return m.focus
}

// Focus focuses the table, allowing the user to move around the rows and
// interact.
func (m *Model) Focus() {
	m.focus = true
	m.UpdateContent()
}

// Blur blurs the table, preventing selection or movement.
func (m *Model) Blur() {
	m.focus = false
	m.UpdateContent()
}

// View renders the component.
func (m *Model) View() string {
	return m.header.View() + "\n" + m.content.View()
}

// HelpView is a helper method for rendering the help menu from the keymap.
// Note that this view is not rendered by default and you must call it
// manually in your application, where applicable.
func (m *Model) HelpView() string {
	return m.Help.View(m.KeyMap)
}

func (m *Model) MoveContentBoundaries(n int) {
	rows := m.VisualRows()

	m.start = clamp(m.start+n, 0, max(0, len(rows)-m.content.Height()))
	m.end = min(m.start+m.content.Height(), len(rows))
}

func (m *Model) updateContentHeight() {
	if m.Height() < 1 || m.cursor < 0 {
		return
	}
	oldLen := m.content.TotalLineCount()
	newLen := m.content.Height()
	diff := oldLen - newLen
	if diff < 0 { // increase
		m.start = max(m.start+diff, 0)
	} else { // decrease
		first := m.cursor - m.start
		m.start = m.start + clamp(diff, 0, first)
	}
	m.end = min(m.start+newLen, len(m.VisualRows()))
}

// UpdateContent updates the list content based on the previously defined
// columns and rows.
// OPTIM: update-content cannot reflect on previous state to determine what rows
// actually require new rendering; therefore, it renders everything, even if the
// row was already included in the viewport contents and its selection-state did
// not change.
func (m *Model) UpdateContent() (updateHeader bool) {
	if m.Height() < 1 || m.cursor < 0 {
		return
	}

	// Render only rows that fit within the viewport
	// Constant runtime, independent of number of rows in a table.
	// Limits the number of renderedRows to a maximum of m.viewport.Height

	// TODO: consider combining loops
	var colChanged bool
	if m.dynCols {
		for j := range m.cols {
			mx := len(m.cols[j].Title)
			for i := m.start; i < m.end; i++ {
				mx = max(mx, len(m.VisualRows()[i][j]))
			}
			colChanged = colChanged || mx != m.cols[j].Width
			m.cols[j].Width = mx
		}
	}

	renderedRows := make([]string, 0, max(0, m.end-m.start))
	for i := m.start; i < m.end; i++ {
		renderedRows = append(renderedRows, m.renderRow(i))
	}

	m.content.SetContent(
		lipgloss.JoinVertical(lipgloss.Left, renderedRows...),
	)

	return colChanged
}

func (m *Model) UpdateHeader() {
	headerRow := m.renderHeader()
	m.header.SetContent(
		lipgloss.JoinVertical(lipgloss.Left, headerRow),
	)
}

// SelectedRow returns the selected row.
// You can cast it to your own implementation.
func (m *Model) SelectedRow() Row {
	rows := m.VisualRows()
	if m.cursor < 0 || m.cursor >= len(rows) {
		return nil
	}

	return rows[m.cursor]
}

// Visual rows returns virtual rows when set or falls back to rows
func (m *Model) VisualRows() []Row {
	if m.virtualRows != nil { // virtualRows with len 0 is valid
		return m.virtualRows
	}
	return m.rows
}

// Rows returns the current rows.
func (m *Model) Rows() []Row {
	return m.rows
}

// VirtualRows returns the current virtual rows.
func (m *Model) VirtualRows() []Row {
	return m.virtualRows
}

// Columns returns the current columns.
func (m *Model) Columns() []Column {
	return m.cols
}

// SetRows sets a new rows state.
func (m *Model) SetRows(r []Row) {
	m.rows = r

	if m.cursor > len(m.VisualRows())-1 {
		m.SetCursor(len(m.VisualRows()) - 1)
	}

	m.UpdateContent()
}

// SetVirtualRows sets the virtual rows
// Note that supplying nil or [] does not reset the view.
// To completely remove virtual rows (even if empty) from view, use the
// `ResetVirtualRows` method.
func (m *Model) SetVirtualRows(r []Row) {
	if r == nil {
		r = []Row{} // ensure this function cannot be abused to replace ResetVirtualRows
	}
	if m.virtualRows == nil && len(r) > 0 { // virtual rows come into view
		m.lastCursor = m.cursor
	}

	m.virtualRows = r

	// OPTIM: perhaps not ideal to hard-set each time
	m.start = 0
	m.end = clamp(m.start+m.content.Height(), m.start, len(r))

	if m.cursor > max(0, len(m.VisualRows())-1) {
		m.SetCursor(len(m.VisualRows()) - 1)
	}

	if colChanged := m.UpdateContent(); colChanged {
		m.UpdateHeader()
	}
}

// resetVirtaulRows empties virtual rows and ensures that the base rows are returned
func (m *Model) ResetVirtualRows() {
	m.virtualRows = nil
	m.cursor = m.lastCursor
}

// SetColumns sets a new columns state.
func (m *Model) SetColumns(c []Column) {
	m.cols = c
	m.UpdateContent()
	m.UpdateHeader()
}

// SetWidth sets the width of the viewport of the table.
func (m *Model) SetWidth(w int) {
	m.content.SetWidth(w)
	m.header.SetWidth(w)
	m.UpdateContent()
	m.UpdateHeader()
}

// SetHeight sets the height of the viewport of the table.
func (m *Model) SetHeight(h int) {
	m.content.SetHeight(h - m.header.Height())
	m.updateContentHeight()
	if colChanged := m.UpdateContent(); colChanged {
		m.UpdateHeader()
	}
}

// Height returns the viewport height of the table.
func (m *Model) Height() int {
	return m.content.Height() + m.header.Height()
}

// Width returns the viewport width of the table.
func (m *Model) Width() int {
	return m.content.Width()
}

// Cursor returns the index of the selected row.
func (m *Model) Cursor() int {
	return m.cursor
}

// SetCursor sets the cursor position in the table.
func (m *Model) SetCursor(n int) {
	n = clamp(n, 0, len(m.VisualRows())-1)
	if m.cursor < n {
		m.MoveUp(n - m.cursor)
	} else {
		m.MoveDown(m.cursor - n)
	}
}

// MoveUp moves the selection up by any number of rows.
// It can not go above the first row.
func (m *Model) MoveUp(n int) {
	m.cursor = clamp(m.cursor-n, 0, len(m.VisualRows())-1)
	if m.cursorOutOfBounds() {
		m.MoveContentBoundaries(-n)
	}
	if colChanged := m.UpdateContent(); colChanged {
		m.UpdateHeader()
	}
}

// MoveDown moves the selection down by any number of rows.
// It can not go below the last row.
func (m *Model) MoveDown(n int) {
	m.cursor = clamp(m.cursor+n, 0, len(m.VisualRows())-1)
	if m.cursorOutOfBounds() {
		m.MoveContentBoundaries(n)
	}
	if colChanged := m.UpdateContent(); colChanged {
		m.UpdateHeader()
	}
}

func (m *Model) cursorOutOfBounds() bool {
	return m.cursor < m.start || m.cursor >= m.end
}

// ScrollRight scrolls the header and viewport contents to the right
func (m *Model) ScrollRight(n int) {
	m.header.ScrollRight(n)
	m.content.ScrollRight(n)
}

// ScrollLeft scrolls the header and viewport contents to the left
func (m *Model) ScrollLeft(n int) {
	m.header.ScrollLeft(n)
	m.content.ScrollLeft(n)
}

// GotoTop moves the selection to the first row.
func (m *Model) GotoTop() {
	m.MoveUp(m.cursor)
}

// GotoBottom moves the selection to the last row.
func (m *Model) GotoBottom() {
	m.MoveDown(len(m.VisualRows()) - 1)
}

// FromValues create the table rows from a simple string. It uses `\n` by
// default for getting all the rows and the given separator for the fields on
// each row.
func (m *Model) FromValues(value, separator string) {
	rows := []Row{} //nolint:prealloc
	for _, line := range strings.Split(value, "\n") {
		r := Row{}
		for _, field := range strings.Split(line, separator) {
			r = append(r, field)
		}
		rows = append(rows, r)
	}

	m.SetRows(rows)
}

func (m *Model) renderHeader() string {
	s := make([]string, 0, len(m.cols))
	for _, col := range m.cols {
		if col.Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(col.Width).MaxWidth(col.Width).Inline(true)
		renderedCell := style.Render(ansi.Truncate(col.Title, col.Width, "…"))
		s = append(s, m.styles.Header.Render(renderedCell))
	}
	return lipgloss.JoinHorizontal(lipgloss.Top, s...)
}

// TODO: render filter match chars with underline or background when appliccable
func (m *Model) renderRow(r int) string {
	s := make([]string, 0, len(m.cols))
	for i, value := range m.VisualRows()[r] {
		if m.cols[i].Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(m.cols[i].Width).MaxWidth(m.cols[i].Width).Inline(true)
		renderedCell := m.styles.Cell.Render(style.Render(ansi.Truncate(value, m.cols[i].Width, "…")))
		s = append(s, renderedCell)
	}

	row := lipgloss.JoinHorizontal(lipgloss.Top, s...)

	if r == m.cursor {
		return m.styles.Selected.Render(row)
	}

	return row
}

func clamp(v, low, high int) int {
	return min(max(v, low), high)
}
