package table

import (
	"strings"

	"charm.land/bubbles/v2/help"
	"charm.land/bubbles/v2/viewport"
	"charm.land/lipgloss/v2"
)

// Model defines a state for the table widget.
type Model struct {
	KeyMap *KeyMap
	Help   help.Model

	// rowCache caches rendered-rows; it is reset upon any table update &
	// sideways scrolling
	rowCache map[int]string

	// fieldDelegate, when set, is called to provide non-default styling for a row
	fieldDelegate FieldDelegate
	// headerDelegate, when set, is called to provide non-default styling for the header
	headerDelegate HeaderDelegate

	dynCols bool

	cols []Column
	// TODO: if rows are already stored in memory in their entirety, can't they
	// 'simply' be passed off to the viewport in their entirety, instead of the
	// complicated viewport content updates that also re-renders every visible
	// line each time.
	rows []Row

	// virtual rows replace rows (visually) when len > 0
	// virtual rows can be used to show filtered data
	virtualRows []Row
	cursor      int
	lastCursor  int // used to reset cursor after a virtual row reset
	focus       bool
	styles      Styles

	content viewport.Model
	header  viewport.Model

	// start & end represent the row indices of the content that is offered to
	// the content viewport, which in this implementation is equal to the rows
	// that are visible.
	start int // inclusive
	end   int // exclusive
}

type FieldDelegate func(row Row, col Column, colIdx, rowIdx, colWidth, padL, padR int, selected, inview bool) string
type HeaderDelegate func(col Column, colIdx, colWidth, padL, padR int) string

// Row represents one line in the table.
type Row struct {
	Fields   []Field
	Metadata map[string]any
}

type Field interface {
	Value() string
}

func (r Row) String() string {
	res := strings.Builder{}
	for _, f := range r.Fields {
		res.WriteString(f.Value())
		res.WriteString(" ")
	}
	return res.String()
}

type Rows []Row

// Convenience function for obtaining plain string representation of each row.
// Useful for searching.
func (r Rows) ToStrings() []string {
	rows := []Row(r)
	res := make([]string, len(rows))
	for i := range rows {
		res[i] = rows[i].String()
	}
	return res
}

// Column defines the table structure.
type Column struct {
	Title        string
	Suffix       string
	Width        int
	DynamicWidth int
	InVisible    bool
}

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header lipgloss.Style
	// only affects default styling, remains unused when using a delegate
	Cell lipgloss.Style
	// only affects default styling, remains unused when using a delegate
	Selected lipgloss.Style
}
